data_dir: data/wrf_wsts_zarr
batch_size: 64
n_leading_observations: 1
crop_side_length: 128
load_from_hdf5: false
load_from_zarr: true
num_workers: 64
remove_duplicate_features: true
features_to_keep: null
n_leading_observations_test_adjustment: 1
split_strategy: spatial
spatial_split_axis: lon
spatial_split_folds: 4
stats_years: null
